Repository Arquisoft/viade_en2b, pull requests merged in 2020-03, with the labels that each got.

#49 Added a basic hamburguer menu and fixed some issues
  .github/ISSUE_TEMPLATE/new-feature-issue-template.md
  package-lock.json
  package.json
  src/assets/css/BurgerMenu.css
  src/components/generic_components/BurgerMenu.js
  src/components/generic_components/GenericButton.js
  src/components/generic_components/MainNavBar.js
  src/components/pages/login.jsx
  src/components/pages/mainPage.jsx
Labels: Front-end, visual

#54 Develop routes list view
  .gitignore
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/assets/css/BurgerMenu.css
  src/assets/css/FixedContainer.css
  src/assets/css/GenericButton.css
  src/assets/css/MainNavBar.css
  src/assets/css/login.css
  src/assets/css/mainPage.css
  src/assets/css/routes.css
  src/assets/img/menu-dot.svg
  src/components/generic_components/BurgerMenu.js
  src/components/generic_components/FixedContainer.js
  src/components/generic_components/GenericButton.js
  src/components/pages/login.jsx
  src/components/pages/mainPage.jsx
  src/components/pages/routes.jsx
  src/components/spec_components/LoginButton.js
Labels: Front-end

#65 Routes list backend
  .gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jsLibraryMappings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/viade_en2b.iml
  .idea/workspace.xml
  package-lock.json
  package.json
  src/Entities/BasicRoute.js
  src/RouteManager/ListUserRoutes.js
  src/components/login/Login.js
  src/components/pages/routes.jsx
  src/data-access/gateways/RouteGateway.js
Labels: Back-end

#61 Feature map view
  .gitignore
  jsconfig.json
  package-lock.json
  package.json
  public/css/main.css
  public/manifest.json
  src/ApiKey.js
  src/App.css
  src/App.js
  src/App.test.js
  src/Entities/Item.js
  src/Entities/Itirenary.js
  src/RouteManager/CreateRoute.js
  src/assets/css/BurgerMenu.css
  src/assets/css/GenericButton.css
  src/assets/css/mainPage.css
  src/components/map_components/MapContainer.js
  src/components/map_components/MapRoute.js
  src/components/map_components/MapStyles.js
  src/components/pages/mainPage.jsx
  src/logo.svg
Labels: enhancement, refactoring

#99 Routes loader parsers tests
  package-lock.json
  src/RouteManager/ListUserRoutes.test.js
Labels: Back-end, testing

#111 Develop improve list and cache
  package-lock.json
  package.json
  public/images/daddy.png
  public/images/searchicon.png
  public/index.html
  src/App.css
  src/App.js
  src/Entities/Friend.test.js
  src/RouteManager/ListUserRoutes.js
  src/assets/css/CustomLoader.css
  src/assets/css/Dropzone.css
  src/assets/css/DropzonePage.css
  src/assets/css/FriendList.css
  src/assets/css/Multiviewer.css
  src/assets/css/SearchBar.css
  src/assets/css/mainPage.css
  src/assets/css/routes.css
  src/caches/routeCache/RouteCache.js
  src/caches/routeCache/RouteCache.test.js
  src/components/generic_components/Card.js
  src/components/generic_components/CustomLoader.js
  src/components/generic_components/SearchBar.js
  src/components/generic_components/SearchBar.test.js
  src/components/login/Login.js
  src/components/map_components/MapContainer.js
  src/components/pages/DropzonePage.js
  src/components/pages/FriendList.js
  src/components/pages/MainPage.js
  src/components/pages/RoutesPage.js
  src/components/pages/RoutesPage.test.js
  src/components/spec_components/Dropzone.js
  src/components/spec_components/MultimediaViewer.js
  src/data-access/gateways/RouteGateway.js
Labels: Front-end, utility

#110 Feature look and feel
  package-lock.json
  package.json
  public/css/main.css
  public/images/icons/favicon.ico
  public/images/img-01.png
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.js
  src/assets/css/BurgerMenu.css
  src/assets/css/FloatingMenu.css
  src/assets/css/GenericButton.css
  src/assets/css/MainNavBar.css
  src/assets/css/login.css
  src/assets/css/mainPage.css
  src/assets/css/routes.css
  src/components/generic_components/FloatingButton.js
  src/components/generic_components/MainNavBar.js
  src/components/generic_components/MainNavBar.test.js
  src/components/generic_components/__snapshots__/MainNavBar.test.js.snap
  src/components/map_components/MapContainer.test.js
  src/components/map_components/MapRoute.test.js
  src/components/map_components/MapStyles.test.js
  src/index.css
Labels: Front-end, visual
